### ISSUE TITLE
Package sending issue SX126x_examples_ESP32

### ISSUE THREAD

**Issue by saroz123** [StuartsProjects/SX12XX-LoRa#101]
package is not sending and can you please help me this.
using this Indiesemic ISC-SX1262-B An advanced LORA module V0.1 Lora Module 
using this code examples/SX126x_examples/ESP32
Sample serial monitor output from transmitter and receiver

104_LoRa_Receiver_Detailed_Setup_ESP32 Starting
LoRa Device found

SX1262,868000000hz,SF7,BW125000,CR4:5,LDRO_Off,SyncWord_0x1424,IQNormal,Preamble_8
SX1262,PacketMode_LoRa,Explicit,LNAgain_Boosted

Reg    0  1  2  3  4  5  6  7  8  9  A  B  C  D  E  F
0x900  30 00...
...
Receiver ready - RXBUFFER_SIZE 32
===========
103_LoRa_Transmitter_Detailed_Setup Starting
LoRa Device found

SX1262,868000000hz,SF7,BW125000,CR4:5,LDRO_Off,SyncWord_0x1424,IQNormal,Preamble_8
SX1262,PacketMode_LoRa,Explicit,LNAgain_Boosted

Reg    0  1  2  3  4  5  6  7  8  9  A  B  C  D  E  F
0x900  30 00 00 00 00 6...
....
Transmitter ready
10dBm Packet> Hello World 1234567890*

**Comment by StuartsProjects** [comment]
I have not seen or tested that module against the library.  The library code is correct and works well.

However, some SX126X modules require specific setup and you would need to contact the device manufacturer for details as to whether they are using a TCXO or not. .

Assuming all the connections are correct one thing you can try is this line in the setup();

LT.setDIO3AsTCXOCtrl(TCXO_CTRL_3_3V);

Either comment it out, so its not executed, or adjust the TCXO voltage to one of the other settings;

TCXO_CTRL_1_6V
TCXO_CTRL_1_7V
TCXO_CTRL_1_8V
TCXO_CTRL_2_2V
TCXO_CTRL_2_4V
TCXO_CTRL_2_7V
TCXO_CTRL_3_0V
TCXO_CTRL_3_3V

Again its really up to the device manufacturer to specify which settings you should use.

**Comment by saroz123** [comment]
Thank you for Quick response!!! Issue got resolved by comment it out

**Comment by StuartsProjects** [comment]
Depends how often the errors are. 

There are no known issues with the library that would cause packet reception errors, so its either a problem with external interference or the modules are faulty. You could try moving them further apart, say 50M or so an see if the problem persists.
