### ISSUE TITLE
readRXDestination() and readRXSource() for SX128XLT.cpp?

### ISSUE THREAD

**Issue by CongducPham** [StuartsProjects/SX12XX-LoRa#26]
Hi, just wondering if there is a reason for SX128XLT.cpp to not have readRXDestination() and readRXSource() functions while SX127XLT.cpp and SX126X.cpp do?

**Comment by StuartsProjects** [comment]
No particular reason. 

readRXDestination() and readRXSource() are not used in any examples, so should have been removed until an example was created to test them. I will create such an example at some point.

**Comment by StuartsProjects** [comment]
No futher action needed.
