### ISSUE TITLE
Is this library 27dBm compatible

### ISSUE THREAD

**Issue by axelJ31** [StuartsProjects/SX12XX-LoRa#32]
I would like to use this module (http://www.ebyte.com/en/product-view-news.html?id=537) and be able to use the 27dBm output power. 
However I'm not sure this library support more than 12dBm.
If the library isn't compatible how could I modify it ?
Thank you for help.

**Comment by StuartsProjects** [comment]
2.4Ghz LoRa modules of that type (more than 12dBm output) normally have no mechanism for setting the power level, which is a problem with the device, not the library. 

The power level is probably 27dBm regardless of what power level the SX1280 is set to. 

The datasheet of the module should have the details.

**Comment by StuartsProjects** [comment]
Not a library issue
