### ISSUE TITLE
Low packet rate of SX1280

### ISSUE THREAD

**Issue by ChSt98** [StuartsProjects/SX12XX-LoRa#35]
Im using the SX1280. I got some code working but seem to hit at limit to how fast i can send packets. Its limited to around 60-70 packets per second regardless of the size. Ive tested with packets containing only 10 bytes and containing over 130 bytes. Both cant send faster than this rate. 
Setting for radio:
```
radio_.setupLoRa(2445000000UL, 0, LORA_SF5, LORA_BW_1600, LORA_CR_4_5);
radio_.setDioIrqParams(IRQ_RADIO_ALL, IRQ_RADIO_ALL, 0, 0);
radio_.setHighSensitivity();
```

And to send im using:
```
radio_.transmit(dataBuffer, sizeof(dataBuffer), 0, 10, NO_WAIT);
```

dataBuffer is always the same size of the data that will be sent. So when sending 10 bytes then sizeof(dataBuffer) returns 10.

Is there something im missing? Im trying to implement a telemetry radio and ive heard of rc systems getting 200hz or more from the sx1280 module.

**Comment by StuartsProjects** [comment]
Its possible that some RC systems have specifically optimised the library code for a fast throughput, there are bits of code in the library routines that are there for reliability and compatibility with the SX126x and SX127x parts of the library that could be probably be removed. 

However the basic examples, 3_LoRa_Transmitter and 4_LoRa_Receiver when removed of all the superfluous serial monitor prints and the like, and run at the fastest LoRa settings, run at 200hz with short packets using humble Arduino 8Mhz Pro Minis. 

As for your code, note that the use of NO_WAIT does mean you need to take care not to start TX again until the runing TX has finished.
