### ISSUE TITLE
DIO1 pin remains HIGH after transmit/receive

### ISSUE THREAD

**Issue by ONLYstcm** [StuartsProjects/SX12XX-LoRa#39]
Doing some debugging and I noticed that DIO1 remains HIGH after a transmit or receive is completed. Looking into the source code, I couldn't seem to find where the pin is reset to LOW. Or a function that can be used to reset the pin. Is this something, that us developers should manually control in our code?

**Comment by StuartsProjects** [comment]
And which LoRa device are you using, DIO1 pin use does vary across the module families ?

**Comment by ONLYstcm** [comment]
I'm using the RFM99W by HopeRF

**Comment by StuartsProjects** [comment]
Which LoRa device does that Hope module use ?

**Comment by ONLYstcm** [comment]
SX1280

**Comment by StuartsProjects** [comment]
DIO1 remains high after completion of RX and TX by design, there is library code to map DIO1 to the appropriate SX128X interrupt.  

DIO1 is reset at the beginning of the transmit() and receive() functions, so see the library code for the IRQ functions that do this.

**Comment by ONLYstcm** [comment]
clearIRQ function worked
