### ISSUE TITLE
Soft WDT reset on ESP8285

### ISSUE THREAD

**Issue by hitesh1402** [StuartsProjects/SX12XX-LoRa#43]

**Comment by hitesh1402** [comment]
Sorted out the issue. Sorry for any inconvenience.

**Comment by StuartsProjects** [comment]
I dont provide support for the ESP8285.

**Comment by hitesh1402** [comment]
Hi,

Thanks for your reply, but the issue was resolved.
Have a great day ahead.



Regards
Hitesh Bhardwaj
________________________________
