### ISSUE TITLE
SX1280,DIO2 as RF switch control

### ISSUE THREAD

**Issue by 01Space** [StuartsProjects/SX12XX-LoRa#47]
Hi，
Can you add a code that uses dio2 pin to control RF switch?

thank you!

**Comment by 01Space** [comment]
Sorry! I didn't check the specification of sx1280 carefully. I consider adding an MCU pin to control the PA switch.
thank you!

**Comment by StuartsProjects** [comment]
Often worthwhile reading the device datasheets. 

The SX128X library does suport the use of external RX and TX enable pins for modules as explained in the documentation.
