### ISSUE TITLE
Low RSSI and SNR values

### ISSUE THREAD

**Issue by VasulBera** [StuartsProjects/SX12XX-LoRa#49]
Hey everyone, I am new to LoRa, have question about transmition power. My setup:
- Ebyte E22-900m30s based on sx1262 chipset.
- Arduino Nano
- Using basic examples for transmitter and reciever, but changed TXpower from 10 to 30.

Reciever is  writing next messages into console:
657s  101*,RSSI,-113dBm,SNR,-11dB,Length,4,Packets,198,Errors,4,IRQreg,16

Distance between LoRa 1-2 meters, which is short. It is stoping recieving messages on 7-8 meters. 
As i understood transmission power is too small, but how can I configure it to make it bigger?
My expectation is to transmit messages to 5 km
Any suggestions?

**Comment by StuartsProjects** [comment]
Very low RSSI and SNR values at short distances are not an issue with the library but are an indication of operating the modules with no effective antenna connected or faulty modules. 

That E22 module appears to hev TXENABLE and RXENABLE pins, do you have them connected and configured ?

**Comment by VasulBera** [comment]
> That E22 module appears to hev TXENABLE and RXENABLE pins, do you have them connected and configured ?

No, Don't know how to connect them/configure, could you give some examples how to do it?

**Comment by StuartsProjects** [comment]
There are note in the Library Readme about TXEANBLE and RXENABLE pins. 

However as mentioned in the ReadMe the use of TXEANBLE and RXENABLE pins is not supported in the SX126X part of the library as I dont have any E22 modules to test.

**Comment by VasulBera** [comment]
> However as mentioned in the ReadMe the use of TXENABLE and RXENABLE pins is not supported in the SX126X part of the library as I dont have any E22 modules to test.
I found this comment in 126X class:
4 Ebyte    > begin(int8_t pinNSS, int8_t pinNRESET, int8_t pinRFBUSY, int8_t pinDIO1, int8_t pinRXEN, int8_t pinTXEN, uint8_t device)

So I  tryied to add TX and RX pins and it helped a little, now RSSI in 1-2 meters ~ -60dbm.
But when I start to make distance bigger in 7-8 meters it is ~ -90dbm.

I know it's not question to the lib, but could you tell me is it normal? and will it work with such params on 5 km?

P.S. Also I found that arduino Nano has 5v logical level but e22 - 3.3v, probably I need converter to each pin used, can it effect LoRa performance?

Thanks in advance

**Comment by StuartsProjects** [comment]
No issue found with library.

**Comment by SlitheringMule** [comment]
What outpuer TX power of SX1262 do you need to output 30dBm from the E22-900M30S?
