### ISSUE TITLE
SX1280 BLE ble packet

### ISSUE THREAD

**Issue by mrninhvn** [StuartsProjects/SX12XX-LoRa#5]
Hi, Can I send BLE packet using sx1280 or not. Thank you very much.

**Comment by LoRaTracker** [comment]
Only LoRa, FLRC and Ranging support and examples have been implemented for SX128X. 

I have no timescale for looking at adding BLE or GFSK.

**Comment by mrninhvn** [comment]
> Only LoRa, FLRC and Ranging support and examples have been implemented for SX128X.
> 
> I have no timescale for looking at adding BLE or GFSK.

I see the definition PACKET_TYPE_BLE in SX128XLT_Definitions.h.
Can I using LT.setPacketType(PACKET_TYPE_BLE)?
Do you have any suggestions about modifying libraries to use BLE?

Thank you again.

**Comment by LoRaTracker** [comment]
Its not simply a case of changing the packet type. 

You need to read the datasheet, it should have the details needed.
