### ISSUE TITLE
Transparent Mode for SX128X with stm32f103 controller

### ISSUE THREAD

**Issue by karthikgn** [StuartsProjects/SX12XX-LoRa#69]
Hi.,

I am trying Transparent mode in sx128X with stm32f103 controller. I am able to transmit from one side and the other side i am receiving the data, but the data has to send from both side not working. Help me to resolve this.

Thank You.,
Regards
Karthik

**Comment by StuartsProjects** [comment]
You will need to explain exactly what you mean by 'Transparent Mode'. 

Which of the library examples use this 'Transparent Mode' ?

**Comment by karthikgn** [comment]
Transparent Mode means full duplex mode, By using TransmitIRQ and ReceiveIRQ in main code its not working to achieve full duplex operation.

**Comment by StuartsProjects** [comment]
The SX128X (and SX126x, SX127X) are half duplex devices, at any one time they can only be in receive or transmit mode.

**Comment by karthikgn** [comment]
SX128X used in ebyte module similar operation has to perform using your library  by using stm32f103 controller, help me to do with your library.

**Comment by StuartsProjects** [comment]
So your trying to replicate the functionality of the eByte E28 modules, why exactly, the eByte modules are low cost ?

**Comment by karthikgn** [comment]
Need only the functionality of the ebyte

**Comment by StuartsProjects** [comment]
Well eByte will be using buffers and timeouts to achieve the impression of full duplex, but that is not actually possible with LoRa devices, they can only be in receive OR transmit mode. 

Thus for your application you will need to switch constantly between receive and transmit modes, and there are plenty of examples showing how this is done in the context of send and acknowledge processes in the \reliable examples folder. There is a lot more to your appplciation than setting appropriate IRQs. 

I provide support for issues\faults with the library and the provided examples, but do not provide free support for custom applications.

**Comment by StuartsProjects** [comment]
The SPI LoRa modules are not capableof full duplex.

**Comment by karthikgn** [comment]
if i use 2 module this can be achieved?
