### ISSUE TITLE
Hello, I ran the modules but they are not communicating.

### ISSUE THREAD

**Issue by serhatbozasb** [StuartsProjects/SX12XX-LoRa#70]
Hello, I ran the modules but they are not communicating.

![l1](https://github.com/StuartsProjects/SX12XX-LoRa/assets/76939389/8696c333-b858-4a0c-b3ff-2911126a4b40)
![l2](https://github.com/StuartsProjects/SX12XX-LoRa/assets/76939389/e7fa5a99-f231-4005-b070-f2b3653d6f76)
 

My schematic is below

[Job1.PDF](https://github.com/StuartsProjects/SX12XX-LoRa/files/12660613/Job1.PDF)

**Comment by serhatbozasb** [comment]
I think the problem is RX and TX pins. I didn't know how to do that part

**Comment by StuartsProjects** [comment]
You need to say which example program you are using and which LoRa module you are using.

**Comment by serhatbozasb** [comment]
I use the following modules with the codes I marked

![lora3](https://github.com/StuartsProjects/SX12XX-LoRa/assets/76939389/3a147e94-b809-4728-8380-22cce0e7d1c8)


![lambda](https://github.com/StuartsProjects/SX12XX-LoRa/assets/76939389/107236b8-7789-4851-91cd-a0e774ec20bd)

**Comment by serhatbozasb** [comment]
LAMBDA62-8S
FM TRANSCEIVER MODULE, 868MHz

**Comment by StuartsProjects** [comment]
The LAMBDA62-8S is an SX1262 based LoRa module. 

The documentation contains a note of SX1262 devices with TX and RX pins;

"**SX126x modules with RX or TX enable pins**"
Some SX126x modules may have RX or TX enable pins, Ebyte E22 modules for instance. Whilst there is code in the SX126X library that was copied across from the SX128X library there were no SX126X devices using RX and TX switching available at the time this library was published, so these functions are currently not supported by the library as they have not been tested. If a user has SX126X modules that they want tested with the library, then donations of modules will be accepted.

So I cannot say if the LAMBDA62-8S will work with the SX126X library.

For an example of using the RX and TX enable pins see examples in the SX128X library.

**Comment by StuartsProjects** [comment]
I dont have suitable modules to test the RX and TX enable pin switching for SX126X devices.
