### ISSUE TITLE
SX1280 | Continual "ERROR - Busy Timeout!"

### ISSUE THREAD

**Issue by GangstaWangstaPranksta** [StuartsProjects/SX12XX-LoRa#77]
### Device:
- NiceRF SX1280
### Code used:
- SX1280 example 3&4 with modified pins and buzzer removed
### Screenshots:
![image](https://github.com/StuartsProjects/SX12XX-LoRa/assets/49811885/2505cbe5-fffe-4126-a985-aa803ed6d747)
![image](https://github.com/StuartsProjects/SX12XX-LoRa/assets/49811885/20d5ca2d-a582-4f0f-8776-7a881f5ef305)
### Additional Info:
The receiver LoRa module does not have NRESET hooked up and is defined as -1, however, this error is occurring with both modules. Pins `DIO1`, `BUSY`, `VCC`, `GND`, `MISO`, `MOSI`, `SCK`, and `NSS` are hooked up in both and are correctly defined in Settings.h. I have tried other examples with the same result. Is this a problem with the code, hardware, or wiring, and any tips to solve this?

**Comment by StuartsProjects** [comment]
The code is fine and has been well tested on the specified hardware for some years.

It looks like your setup is reading a constant high on the RFBUSY pin. 

Can you provide a link to the actual SX1280 module you are using, the Arduino your using and the pin definitions you are using ?

As an asside I would not use a SX1280 without the NRESET pin, you can get away without it on SX127X modules but if its missing there can be reliability issues with SX128X and SX126X modules.

**Comment by GangstaWangstaPranksta** [comment]
I am using the NiceRF SX1280 with an Elegoo Arduino Uno. Below is a screenshot of the pin definitions from Settings.h.
I'll add a connection to the NRESET pin when I get a chance, I just happened to miss it while soldering and went with it to see if I could do without it.

![image](https://github.com/StuartsProjects/SX12XX-LoRa/assets/49811885/b13ff55d-e881-4a25-8139-92edb055d3c5)

**Comment by StuartsProjects** [comment]
> Elegoo Arduino Uno

That is a 5V logic Arduino I believe ?

You cannot use 5V logic Arduinos direct with the 3.3V Logic level LoRa devices.  The LoRa modules can be damadged too.

**Comment by StuartsProjects** [comment]
Not a library issue. There are warning in the documentation about using LoRa devices on 5V Arduinos.
