### ISSUE TITLE
The modulation settings for the SX1268 chip do not work correctly - E22-400M30s

### ISSUE THREAD

**Issue by piotrret** [StuartsProjects/SX12XX-LoRa#79]
Hello, first of all I would like to say that the library you wrote is very cool and extremely helpful.
I only encountered one small problem.
I use the Ebyte E22-400m30s module and I did tests using the code from the example [https://github.com/StuartsProjects/SX12XX-LoRa/blob/master/examples/SX126x_examples/Basics/58_FM_Tone/58_FM_Tone.ino](url)
The code contains parameter deviation = 10000, but no matter what value I set, it does not affect the modulation depth of the FM signal. In addition, the output signal is terribly distorted and contains a lot of harmonics. Previously, I tested with the Ra-02 module containing the SX1278 chip and the FM signal was generated correctly - I could change the modulation in the program.
For the SX1278 module I used an example [https://github.com/StuartsProjects/SX12XX-LoRa/blob/master/examples/SX127x_examples/Basics/58_FM_Tone/58_FM_Tone.ino](url) that is very similar.

**Comment by StuartsProjects** [comment]
No support for the Tone functions on modules that have a RF PA added.
