### ISSUE TITLE
Compatibility of LoRa Chips: Using SX1262 as Sender and SX1278 as Receiver

### ISSUE THREAD

**Issue by khalidalbasheer** [StuartsProjects/SX12XX-LoRa#81]
I’m working on a project that involves LoRa communication, and I’d like to explore using different LoRa chip models. Specifically, I want to use the Semtech SX1262 as the sender (transmitter) and the SX1278 as the receiver.
My goal is to achieve reliable, long-range communication between these two chips.

Is it feasible to pair the SX1262 and SX1278 in this way?

**Comment by StuartsProjects** [comment]
The SX126X and SX127X are compatible from SF7 and above. 

The SX126X normally use a TCXO for frequency control and can be used at lower bandwidths than the SX127X. 

These are limitations of the devices and nothing to do with this library.

**Comment by khalidalbasheer** [comment]
So, based on your comment, I can send packets from SX126X to SX127X using your amazing library.
I note that your library settings use SF7.
Is that true?

**Comment by khalidalbasheer** [comment]
So, based on your comment, I can send packets from SX126X to SX127X using your amazing library.
I note that your library settings use SF7.
The device I want to use is ESP32 board with LoRa built-in chip produced by Heltec Automation
![esplora](https://github.com/StuartsProjects/SX12XX-LoRa/assets/15718538/7ff97d39-d39e-430c-b4d8-6f1ec5507dd7)

**Comment by StuartsProjects** [comment]
You adjust the LoRa settings to suit the application.

**Comment by StuartsProjects** [comment]
No issues with the library.
