### ISSUE TITLE
"No device responding" on LoRaReceive for WifiKit 32 V3

### ISSUE THREAD

**Issue by Frosty-STI** [StuartsProjects/SX12XX-LoRa#83]
I have one WiFiKit 32 V3 flashed with the basic LoRa transmit code, and another flashed with the basic LoRa receive code. The transmitter side is printing this to the serial monitor:

3_LoRa_Transmitter Starting
Guru Meditation Error: Core  1 panic'ed (Unhandled debug exception). 
Debug exception reason: Stack canary watchpoint triggered (loopTask) 
Core  1 register dump:
PC      : 0x4037cf6b  PS      : 0x00060036  A0      : 0x8037bbac  A1      : 0x3fce9fa0  
A2      : 0x3fc92fd0  A3      : 0xb33fffff  A4      : 0x0000cdcd  A5      : 0x00060023  
A6      : 0x00060023  A7      : 0x0000abab  A8      : 0xb33fffff  A9      : 0xffffffff  
A10     : 0x3fc92fa8  A11     : 0x00000001  A12     : 0x00060021  A13     : 0x3fcea070  
A14     : 0x02c92fd0  A15     : 0x00ffffff  SAR     : 0x00000007  EXCCAUSE: 0x00000001  
EXCVADDR: 0x00000000  LBEG    : 0x420037ac  LEND    : 0x420037bb  LCOUNT  : 0x00000000  

Backtrace: 0x4037cf68:0x3fce9fa0 0x4037bba9:0x3fce9fe0 0x4037a4c4:0x3fcea010 0x4037a4ba:0xa5a5a5a5 |<-CORRUPTED

ELF file SHA256: 2791cb5f16ef86f7

Meanwhile the receiver side is printing this to the serial monitor:
�I�H��90F��
4_LoRa_Receiver Starting

No device responding

**Comment by StuartsProjects** [comment]
You need to make sure the pin number allocations in the sketch are correctly changed to match your board. 

On some ESP32 based boards you may need to change the SPI.begin(); command to identify the pin numbers for the SPI SCK, MISO and MOSI pins to this;

SPI.begin(SCK, MISO, MOSI);

Replacing SCK, MISO, MOSI with the pin numbers for you board.
