### ISSUE TITLE
Heltec Lora32 V3

### ISSUE THREAD

**Issue by hoka83** [StuartsProjects/SX12XX-LoRa#88]
does this library support Heltec lora 32 V3 board ?

**Comment by StuartsProjects** [comment]
The library has not been tested against the 'Heltec lora 32 V3 board' and there do seem to be some variations in the board. 

Unfortunatly the manufactures of boards dont donate them to me for testing.

**Comment by StuartsProjects** [comment]
The manufacture of the 'Heltec lora 32 V3 board' will need to supply the appropriate pins to use for connections. If the pins are defined correctly the libraryy examples should work.
