### ISSUE TITLE
LoRaWAN support

### ISSUE THREAD

**Issue by Dimah4x** [StuartsProjects/SX12XX-LoRa#91]
is it possible to restructure the packets to add lorawan support to this project?

**Comment by StuartsProjects** [comment]
It should be possible, LoRaWAN at the basic level just sends and receives LoRa packets. 

However working out what to put in the packets and how to interpret whats in the received ones would probably take you a while to work out.

**Comment by StuartsProjects** [comment]
The library has no support for LoRaWAN
