### ISSUE TITLE
Sending polling requests to remote nodes for the return of specific data.

### ISSUE THREAD

**Issue by TheLittleYellowFiat** [StuartsProjects/SX12XX-LoRa#94]
Hello, I saw that in the README file, there's mentions of `Sending polling requests to remote nodes for the return of specific data.`, but I couldn't find any examples that use this feature, nor could I find a library function that might be used for this. Could you point me in the right direction to use this feature?

**Comment by StuartsProjects** [comment]
See the examples in the \Reliable folder with 'Request' in the sketch name.
