### ISSUE TITLE
SX1278 esp32Cam getting the transmitters battery voltage

### ISSUE THREAD

**Issue by perrer12** [StuartsProjects/SX12XX-LoRa#95]
Hello,

i use the ESP32Cam as Transmitter an an ESP32 Wrover as Receiver to transmit a picture from the examples, which works fine.

I read the Battery Voltage on Pin 14 of the ESP32cam and tried to transmit this after the picture was succesfully sent.

For this, i used the simple LoRa.transmit and LoRa.receive from the basic examples, but after receiving the picture, i get a timeout und no data was received.

Whats the best way to send the battery voltage to the receiver after receiving the picture ?

Thanks in advance

Perrer

**Comment by perrer12** [comment]
I also use LittleFS for transmitter and receiver, so i got Pin 14 for analog read

**Comment by StuartsProjects** [comment]
LoRa.transmit() and LoRa.receive() functions use DIO0 to detect TX and RX complete. 

But the ESP32CAM does not use DIO0, which is why all the transfer code uses the IRQ versions of transmit and receive. 

See the examples 3_LoRa_TransmitterIRQ and 4_LoRa_ReceiverIRQ

**Comment by perrer12** [comment]
With using IRQ, it works now.

Thank you very much !
