### ISSUE TITLE
Wrong pin definitions in sketch comments

### ISSUE THREAD

**Issue by JamesHamilton4** [StuartsProjects/SX12XX-LoRa#97]
Pin definitions mentioned in comments at start of sketch:
241_StuartCAM_ESP32CAM_LoRa_Receiver.ino
differ from the pin definitions in the Settings.h file.
This may cause confusion.

**Comment by StuartsProjects** [comment]
Well spotted. The comments were indeed wrong, that was a previous pin layout. The sketch has been updated.

Thanks.

**Comment by StuartsProjects** [comment]
Closed
